CREATE TABLE User (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Username TEXT NOT NULL,
    Password INTEGER NOT NULL
);

CREATE TABLE Token (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Token TEXT NOT NULL,
    UserId INTEGER NOT NULL,
    FOREIGN KEY(UserId) REFERENCES User(Id)
);